configuration: Release

install:
  - choco install gitversion.portable -pre -y
  - git submodule update --init --recursive

assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo SharedAssemblyInfo.cs
  - ps: |
      $jsonpath = 'src/WeCantSpell.Hunspell/project.json'
      $json = Get-Content -Raw -Path $jsonpath | ConvertFrom-Json
      $json.version = $Env:GitVersion_NuGetVersion
      $json | ConvertTo-Json -depth 999 | Out-File $jsonpath

build:
  project: WeCantSpell.Hunspell.sln

after_build:
  - cmd: dotnet pack src/WeCantSpell.Hunspell -c Release
  - cmd: appveyor PushArtifact "src/WeCantSpell.Hunspell/bin/Release/WeCantSpell.Hunspell.%GitVersion_NuGetVersion%.nupkg"